name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -haltr
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls -haltr
      
      - name: Show current user
        run: whoami
        
      - name: Show user groups
        run: groups

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '14'
      # - run: npm install -g bats
      # - run: bats -v
